#include "txn_capture.h"
#ifndef NATIVE_TEST
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "txn_capture.pio.h"   /* generated by pico_generate_pio_header */

#define TX_PIO       pio1
#define TX_SM        0u
#define TX_RING_BITS 14u                          /* 16 KB ring → write-addr wrap */
#define TX_RING_LEN  (1u << (TX_RING_BITS - 2))   /* 4096 u32 entries             */

__attribute__((aligned(1u << TX_RING_BITS))) static volatile uint32_t tx_ring[TX_RING_LEN];

static uint tx_off;
static int  tx_dma = -1;
static uint32_t tx_rd, tx_waddr_total, tx_waddr_prev, tx_disc;

static void tx_arm_dma(void) {
    dma_channel_config c = dma_channel_get_default_config(tx_dma);
    channel_config_set_transfer_data_size(&c, DMA_SIZE_32);
    channel_config_set_read_increment(&c, false);
    channel_config_set_write_increment(&c, true);
    channel_config_set_ring(&c, true, TX_RING_BITS);   /* wrap WRITE address */
    channel_config_set_dreq(&c, pio_get_dreq(TX_PIO, TX_SM, false));
    dma_channel_configure(tx_dma, &c, (void *)tx_ring, &TX_PIO->rxf[TX_SM],
                          dma_encode_endless_transfer_count(), true);
}

static void tx_start_sm(void) {
    pio_sm_config c = txn_read_capture_program_get_default_config_custom(tx_off);
    pio_sm_init(TX_PIO, TX_SM, tx_off, &c);
    pio_sm_set_consecutive_pindirs(TX_PIO, TX_SM, 0, 32, false);
    pio_sm_clear_fifos(TX_PIO, TX_SM);
    pio_sm_set_enabled(TX_PIO, TX_SM, true);
}

void txn_capture_init(void) {
    tx_off = pio_add_program(TX_PIO, &txn_read_capture_program);
    tx_dma = dma_claim_unused_channel(true);
    tx_arm_dma();
    tx_start_sm();
    tx_rd = tx_waddr_total = tx_waddr_prev = tx_disc = 0;
}

void txn_capture_reset(void) {
    if (tx_dma < 0) return;
    pio_sm_set_enabled(TX_PIO, TX_SM, false);
    dma_channel_abort(tx_dma);
    pio_sm_clear_fifos(TX_PIO, TX_SM);
    pio_sm_restart(TX_PIO, TX_SM);
    pio_sm_exec(TX_PIO, TX_SM, pio_encode_jmp(tx_off));
    tx_arm_dma();
    pio_sm_set_enabled(TX_PIO, TX_SM, true);
    tx_rd = tx_waddr_total = tx_waddr_prev = tx_disc = 0;
}

void txn_capture_stop(void) {
    if (tx_dma < 0) return;
    pio_sm_set_enabled(TX_PIO, TX_SM, false);
    dma_channel_abort(tx_dma);
}

static uint32_t tx_dma_total(void) {
    uint32_t waddr = dma_hw->ch[tx_dma].write_addr;
    uint32_t base  = (uint32_t)(uintptr_t)tx_ring;
    uint32_t cur   = ((waddr - base) & ((1u << TX_RING_BITS) - 1u)) >> 2;
    uint32_t delta = (cur - tx_waddr_prev) & (TX_RING_LEN - 1u);
    tx_waddr_total += delta;
    tx_waddr_prev   = cur;
    return tx_waddr_total;
}

uint32_t txn_capture_drain(bus_integrity_t *bi) {
    if (tx_dma < 0) return 0;
    uint32_t total = tx_dma_total();
    uint32_t rd = tx_rd;
    if (total - rd > TX_RING_LEN) {            /* overrun guard (see boot_capture) */
        tx_disc += (total - rd) - TX_RING_LEN;
        rd = total - TX_RING_LEN;
    }
    uint32_t n = 0;
    for (; rd != total; rd++) {
        uint32_t raw = tx_ring[rd & (TX_RING_LEN - 1)];
        bus_integrity_feed(bi, (uint16_t)(raw & 0xFFFFu),
                           (uint8_t)((raw >> 16) & 0xFFu));
        n++;
    }
    tx_rd = rd;
    return n;
}
#endif /* !NATIVE_TEST */
